name: C++ GVNS

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  gcc-cmake-ctest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release --parallel 2
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
